version: '3'
services:
  backend-gateway:
    container_name: backend-gateway
    build:
      context: ./backend-gateway
      dockerfile: Dockerfile
    ports:
      - "8101:8101"
    networks:
      - mynetwork
    deploy:
      resources:
        limits:
          memory: 512M


  backend-user-service:
    container_name: backend-user-service
    build:
      context: ./backend-user-service
      dockerfile: Dockerfile
    ports:
      - "8102:8102"
    networks:
      - mynetwork
    depends_on:
      - backend-gateway
    deploy:
      resources:
        limits:
          memory: 256M

  backend-question-service:
    container_name: backend-question-service
    build:
      context: ./backend-question-service
      dockerfile: Dockerfile
    ports:
      - "8103:8103"
    networks:
      - mynetwork
    depends_on:
      - backend-user-service
      - backend-gateway
    deploy:
      resources:
        limits:
          memory: 600M

  backend-judge-service:
    container_name: backend-judge-service
    build:
      context: ./backend-judge-service
      dockerfile: Dockerfile
    ports:
      - "8104:8104"
    networks:
      - mynetwork
    depends_on:
      - backend-user-service
      - backend-question-service
      - backend-gateway
    deploy:
      resources:
        limits:
          memory: 512M

  sandbox-code:
    container_name: sandbox-code
    build:
      context: ./sandbox-code
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    networks:
      - mynetwork
    deploy:
      resources:
        limits:
          memory: 300M

networks:
  mynetwork:
